- README.rst
- app/dalton.py
- app/templates/dalton/coverage-summary.html
- app/templates/dalton/coverage.html
Controller API additions to facilitate programmatic submissions which still have to mimic web submissions so still a ways to go there but this is a start.
README additions and tweaks.
> Controller API Additions

- app/static/engine-configs/suricata/suricata-4.0.3.yaml
Only a minor change:
```
401a402
>       append: yes       # append to file (yes) or overwrite it (no)
```
> default yaml file for suricata-4.0.3

- dalton-agent/Dockerfiles/Dockerfile_suricata
- docker-compose.yml
added rust packages to Suricata agents before they compile Suricata.
> updated what versions of Suricata get built by default

- dalton-agent/dalton-agent.py
Add 'dalton_web' to 'no_proxy' environment for Dalton Agent when it starts.
Added simple local (info) logging for agents when they process a job.
> Agent proxy help

- .gitignore
(but not docker-compose that has the agent definitions)
> track Docker files in Git 

- README.rst
- app/dalton.py
- app/templates/dalton/coverage-summary.html
- app/templates/dalton/coverage.html
- app/templates/dalton/job.html
- app/templates/dalton/queue.html
- app/templates/dalton/sensor.html
- dalton-agent/Dockerfiles/Dockerfile_suricata_rust
- dalton-agent/dalton-agent.py
- docker-compose.yml
Support for easily building and using Suricata agents that have Rust support.  Includes new Dockerfile specific for compiling with Rust.
> Suricata Agent - Rust support

- app/templates/dalton/coverage.html
Based on PR 118 from donaciano
> Prevent horizontal scroll bar.

- app/static/engine-configs/suricata/suricata-4.1.5.yaml
- app/static/engine-configs/suricata/suricata-5.0.0.yaml
- docker-compose.yml
updated configs, docker-compose, etc.
> tweaks for Suricata 5

- app/dalton.py
- app/templates/dalton/coverage.html
Keeps the current method of multiple pcaps but changed to a multiple select file dialog for each.
> Allow for both methods of multiple pcaps

- requirements.txt
Added requirement for `itsdangerous==2.0.1`
> Added itsdangerous explicitly in requirements to fix Flask issue

- requirements.txt
> Specify Jinja2 version in requirements

- README.rst
- app/flowsynth.py
- also ran isort
This PR is a re-creation of #173 which didn't look right when I came to review it.
Closes #172
> Be able to pre-fill the flowsynth compile page via GET or POST

- CHANGELOG.rst
Added tags and descriptions of recent work.
> Updated changelog file.

- CHANGELOG.rst
- Dockerfile-dalton
- pyproject.toml
- requirements.txt
- updated Dockerfile-dalton
- emptied out the requirements.txt file
> Use pyproject.toml (#184)

- Makefile
- api/dalton.py
- api/examples/job_submission.py
- app/certsynth.py
- app/dalton.py
- app/flowsynth.py
- pyproject.toml
- Simply ran `ruff format`
- Issue #183
> Run ruff format to standardize file formatting

- .github/workflows/python-app.yml
- CHANGELOG.rst
- updated the changelog
- closes #191
> Added github CI workflow

- dalton-agent/dalton-agent.py
- pyproject.toml
Follow on from #183 
Also run the linters on the dalton-agent directory
Automated fixes and a small number of manual fixes
> Also lint dalton agent

- CHANGELOG.rst
- Makefile
- app/flowsynth.py
- pyproject.toml
- tests/conftest.py
- tests/files/pcap_98765.pcap
- tests/test_dalton.py
- tests/test_factory.py
- tests/test_flowsynth.py
- Small refactoring
- Small tweaks to comments
- Update Makefile
- Properly show any flowsynth errors
Closes #204
> Add unit tests for the flowsynth web UI

- CHANGELOG.rst
- app/dalton.py
- pyproject.toml
- tests/test_dalton.py
- ruff found a couple of good fixes
- added a unit test for dalton
Closes #209
> Additional code checking by ruff

- CHANGELOG.rst
- Makefile
- dalton-agent/Dockerfiles/Dockerfile_snort
- dalton-agent/Dockerfiles/Dockerfile_suricata
- dalton-agent/Dockerfiles/Dockerfile_zeek
- slight tweaks to the Dockerfiles
- ran hadolint
Closes #181
> Use pre-built zeek images

- app/dalton.py
You cannot any longer set a boolean in redis
Closes #213
> job results boolean bug with zeek and json

- app/dalton.py
Need to treat the zeek_json as a string not an integer.
Closes #213
> Zeek results were not being shown

- CHANGELOG.rst
- app/__init__.py
- pyproject.toml
Just upping the version and adding a changelog entry
> Bump version: 3.4.0 → 3.4.1

- CHANGELOG.rst
- Dockerfile-dalton
- app/__init__.py
- docker-compose.yml
- pyproject.toml
- Start the app with the `flask` command line tool
- Compress is not needed since we are behind nginx
- Cacheing is not particularly necessary, and adds complexity
- We are not using `Flask-Script` or `Flask-Assets`
- Allow large file uploads
Issue #180
> Update flask dependencies

- app/flowsynth.py
> Ruff wants to add a space here
